config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index",as: :about


  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "sign_up", to: "registrations#new", as: :signup
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new", as: :signin
  post "sign_in", to: "sessions#create"

  delete "log_out", to: "sessions#destroy", as: :logout

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets
  

  root to: "main#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, presence: true , length: {minimun: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 12.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: self.publish_at).perform_later(self)
    end
  end
  def published?
    tweet_id? 
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
  
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets
  belongs_to :user

  validates :username, presence: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string (virtual attribute)
# password_confirmation:string (virtual attribute)
class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets
    
    has_secure_password

    validates :email, presence: true , format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ , message: "Invalid email format" }
    validates :password, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find(session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: 'You must be logged in to access this page.' if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        Rails.logger.info auth
        Current.user.twitter_accounts.create(
            name: auth.info.name,
            username: auth.info.nickname,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret,
        )

        redirect_to twitter_accounts_path, notice: "Twitter account added 🎉"
    end

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email].downcase)
        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        flash[:notice] = "If there is an account associated with #{params[:email]}, you will receive an email with instructions on how to reset your password in a few minutes."
        redirect_to password_reset_url
    end

    def edit
        @user = User.find_signed(params[:token], purpose: "password_reset")
        if @user.blank?
            flash[:alert] = "Invalid or expired password reset token."
            redirect_to signin_url
        end

    end

    def update
        @user = User.find_signed(params[:token], purpose: "password_reset")
        if @user.update(user_params)
            flash[:notice] = "Password has been reset."
            redirect_to signin_url
        else
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:password, :password_confirmation)
    end


end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit

    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: 'Your password has been changed.'
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, notice: "Logged in!"  
    else
        flash[:alert] = "Invalid email or password"
        redirect_to sign_in_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:show, :edit, :update, :destroy]

    def index
        @tweets = Current.user.tweets.order(created_at: :desc)
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            redirect_to tweets_path, notice:  "Tweet was successfully scheduled🎉"
        else
            flash.now[:danger] = "An error occurred while scheduling your tweet😞"
            render :new
        end
    end

    def show
    end
    

    def edit
    end

    def update
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Tweet was successfully updated🎉"
        else
            flash.now[:danger] = "An error occurred while updating your tweet😞"
            render :edit
        end
    end

    def destroy
        @tweet.destroy
        redirect_to tweets_path, notice: "Tweet was successfully deleted🎉"
    end



    private

    def tweet_params
        params.require(:tweet).permit(:twitter_account_id,:body, :publish_at)
    end

    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]
    def index
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_account.destroy
        redirect_to twitter_accounts_path, notice: "Successfully disconnected @#{@twitter_account.username} from your account ✔" 
    end

    private
    def set_twitter_account
        @twitter_account = Current.user.twitter_accounts.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduletweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <!-- Popperjs -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.2/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <!-- Tempus Dominus JavaScript -->
    <script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"  crossorigin="anonymous"></script>

    <!-- Tempus Dominus Styles -->
    <link href="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css" rel="stylesheet" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render  partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex aling-items-center justify-content-center">
        <h1 >
            Welcome to the Scheduled Tweets!
        </h1>        
</div>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-auto mt-5 ">
        <%= button_to "Connect Twitter Account 🎈", "/auth/twitter", method: :post, data: {turbo: "false"} ,class: "btn btn-primary" %>
    </div>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset password for <%= @user.email %></h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <div class="mb-3">
        <%= form.label :password, class: "form-label"%>
        <%= form.password_field :password, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label"%>
        <%= form.password_field :password_confirmation, class: "form-control"%>
    </div>
    <%= form.submit "Reset Password", class: "btn btn-primary"%>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>
<p>Enter your email address below and we'll send you a link to reset your password.</p>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email, class: "form-label"%>
        <%= form.text_field :email, class: "form-control", placeholder: "example@domain.com"%>
    </div>
    <%= form.submit "Send Reset", class: "btn btn-primary"%>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message|%>
                <div><%= message %></div>
            <% end %>
        </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
             <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link" %> 
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, password_path , class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, class: "btn btn-sm btn-outline-secondary" , method: :delete   %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "btn btn-outline-success me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", signin_path, class: "btn btn-outline-secondary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
    <div class="mb-3">
        <%= form.label :twitter_account_id %>
        <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts.all, :id, :username, {}, {class: "form-select"} %>
    </div>

    <div class="mb-3">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :publish_at %>
        <div class="form-control">
            <%= form.datetime_select :publish_at %>
        </div>
    </div>

    <%= form.button "Schedule", class: "btn btn-primary" %>

    <% if form.object.persisted? %>
        <%= link_to "Yes Delete", form.object , method: :delete ,class: "btn btn-danger" %>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Delete Tweet
        </button>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    You are about to delete the Tweet bellow:
                    <div class="card card-body">
                        <a class="d-flex align-items-center" href="<%="https://twitter.com/#{form.object.twitter_account.username}"%>">
                            <%= image_tag form.object.twitter_account.image, class: "rounded-circle" unless form.object.twitter_account.image.nil?%>
                            <div class="d-flex flex-column px-2">
                                <div class="fw-bold"><%=form.object.twitter_account.name%></div>
                                <div>@<%= form.object.twitter_account.username%></div>
                            </div>
                        </a>
                        <div class="fs-4 mt-3"><%= form.object.body %></div>
                        <div class="fs-6 text-secondary">
                            Scheduled for:<%= form.object.publish_at.strftime("%l:%M %p • %b %e,%Y") %>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="col-md-auto mt-5 ">
    <div class="card" style="min-width: 20rem">
        <div class="card-body">
            <a class="d-flex align-items-center" href="<%="https://twitter.com/#{tweet.twitter_account.username}"%>">
                <%= image_tag tweet.twitter_account.image, class: "rounded-circle" unless tweet.twitter_account.image.nil?%>
                <div class="d-flex flex-column px-2">
                    <div class="fw-bold"><%=tweet.twitter_account.name%></div>
                    <div>@<%= tweet.twitter_account.username%></div>
                </div>
            </a>
            <div class="fs-4 mt-3"><%= tweet.body %></div>
            <% if tweet.published? %>
               <div class="fs-6 text-secondary"><%= tweet.updated_at.strftime("%l:%M %p • %b %e,%Y") %></div>
                <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
            <% else %>
               <div class="fs-6 text-secondary"> Scheduled for:<%= tweet.publish_at.strftime("%l:%M %p • %b %e,%Y") %></div>
            <% end %>
            <hr/>
            <%= link_to "Edit Tweet", edit_tweet_path(tweet), class: "btn btn-primary" %>
        </div>

    </div>
</div>

app/views/tweets/edit.html.erb
<div class="d-flex aling-items-center justify-content-center">
    <h1>Edit Scheduled a Tweet📝</h1>
</div>

<%= render "form", tweet: @tweet %>



           
           

app/views/tweets/index.html.erb
<div class="d-flex aling-items-center justify-content-center">
    <h1> Tweets </h1>
</div>


<% if Current.user.twitter_accounts.none? %>
        <div class="text-center">
            <div class="col-md-auto  mt-5">
                    <h2>Sorry not connected to any account😢</h2>
                    <h3>Please click the button below to connect</h3>
                </div>
            <div class="col-md-auto mt-5 ">
                <%= button_to "Connect Twitter Account 🎈", "/auth/twitter", method: :post, data: {turbo: "false"} ,class: "btn btn-primary" %>
            </div>
        </div>
<% end %>

<% if Current.user.twitter_accounts.any? %>
    <div class="container">

            <div class="col-md-auto mt-5 d-flex align-items-center justify-content-center">
                 <%= link_to "New Tweet 📝", new_tweet_path, class: "btn btn-primary"%>
            </div>
        <div class="row justify-content-md-center">
            <%= render @tweets %>
        </div>
    </div>
<% end %>

app/views/tweets/new.html.erb
<div class="d-flex aling-items-center justify-content-center">
    <h1>Schedule a tweet</h1>
</div>

<%= render "form", tweet: @tweet %>




           
           

app/views/twitter_accounts/index.html.erb
<div class="d-flex aling-items-center justify-content-center">
    <h1>Twitter Accounts</h1>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <% @twitter_accounts.each do |twitter_account|%>
        <div class="col-md-auto mt-5 ">
            <div class="card">
                <div class="card-body justify-content-center">
                        <a class="d-flex align-items-center" href="<%="https://twitter.com/#{twitter_account.username}"%>">
                            <%= image_tag twitter_account.image, class: "rounded-circle" unless twitter_account.image.nil?%>
                            <div class="d-flex flex-column px-2">
                                <div class="fw-bold"><%=twitter_account.name%></div>
                                <div>@<%= twitter_account.username%></div>
                            </div>
                        </a>
                    <button type="button" class="btn btn-danger mt-4 " data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Disconnect Account
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                You are about to disconnect from the Twitter Account bellow:
                                <div class="card">
                                    <div class="card-header d-flex align-items-center justify-content-center">
                                        <%= image_tag twitter_account.image, class: "rounded-circle" unless twitter_account.image.nil? %>
                                        <h4 class="card-title px-2"><%= link_to "#{twitter_account.name}", "https://twitter.com/#{twitter_account.username}", target: :_blank %></h4>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <%= button_to "Yes disconnect", twitter_account, method: :delete ,class: "btn btn-danger" %>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <div class="col-md-auto mt-5 d-flex align-items-center justify-content-center">
        <%= button_to "Connect New Account 🎈", "/auth/twitter", method: :post, data: {turbo: "false"} ,class: "btn btn-primary" %>
    </div>
</div>